[package]
name = "lume-reference-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
lume-protocol = { path = "../lume-protocol" }
lume-sdk = { path = "../lume-sdk" }
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
