[package]
name = "lume-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde.workspace = true
tauri = { version = "2.11.5", features = [] }

[lints]
workspace = true
